export const Settings = {
    DISPLAY_BOUNDING_BOXES: false,
    DISPLAY_CONTACT_POINTS: false,
    DISPLAY_SHADOWS: true,
    DISPLAY_INFINITE_SPATIAL_HASH_GRID: false,
    WIREFRAME: false,
    USE_DYNAMIC_INERTIA_TENSOR: true,
    MAX_DEPTH: 7,
    EPSILON: 0.05,
    DEFAULT_RESTITUTION: 0.7,
    DEFAULT_FRICTION: 0.9,
};
